services:
  - type: web
    name: artvista-backend
    env: docker
    plan: free
    dockerCommand: "mvn clean install -DskipTests && java -jar target/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: artvista-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: artvista-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: artvista-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: artvista-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: artvista-db
          property: password
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: artvista-db
    databaseName: artvista
    user: artvista_admin
    plan: free
